### ISSUE TITLE
Animal DB [AWS RDS]

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/intro-to-k8s#7]
Spin up a [https://github.com/typicode/lowdb](LowDB) instance to store all of the links to images and cat

```json
{
       category: "cat",
       link: "awslink.com/s3",
       name: "Cat in the rain", 
}
```

**Comment by emsesc** [comment]
![image](https://user-images.githubusercontent.com/69332964/123862327-348ad400-d8f6-11eb-9b0b-f9bfa363b5fd.png)
